version: '3'

services:
  app:
    image: tolgee/tolgee
    volumes:
      - ./data:/data
      - ./config.yaml:/config.yaml
    ports:
      - '25432:25432'
      - '8080:8080'
    env_file:
      - .env

