name: i18n Analyze and Upload

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    outputs:
      missing: ${{ steps.count.outputs.missing }}
      unused: ${{ steps.count.outputs.unused }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package.json', 'pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run i18n-analyze script
        run: npm run i18n-analyze

      - name: Count keys
        id: count
        run: |
          MISSING=$(jq 'keys | length' scripts/missing-key.json)
          UNUSED=$(jq 'keys | length' scripts/unused-key.json)
          echo "missing=$MISSING" >> $GITHUB_OUTPUT
          echo "unused=$UNUSED" >> $GITHUB_OUTPUT
      
      - name: Upload analyze result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: i18n-result
          path: |
            scripts/missing-key.json
            scripts/unused-key.json